#!/usr/bin/env python3
"""Generate a longer terminal demo script for spec-harness."""

import time
import sys

def type_text(text, delay=0.02):
    for char in text:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(delay)
    sys.stdout.write('\n')
    sys.stdout.flush()
    time.sleep(0.3)

# Title
type_text("$ # Step 1: Initialize a project")
type_text("$ spec-harness init --name my-erp")
type_text("")
type_text("Initialized project 'my-erp'")
type_text("  requirements/  - Place requirement .md files here")
type_text("  outputs/    - Generated artifacts will appear here")
type_text("")
type_text("$ # Step 2: Generate specs from a requirement document")
type_text("$ spec-harness generate examples/requirements/attachment_management.md")
type_text("")

# Output with colors (simulated with ANSI codes)
type_text("\033[34mParsed requirement:\033[0m Requirement: Unified Attachment Management")
type_text("\033[34mDomain analysis:\033[0m 7 ops, 12 objects")
type_text("\033[32mGenerated 6 user stories\033[0m")
type_text("\033[32mGenerated acceptance criteria\033[0m")
type_text("\033[32mGenerated domain_model.yaml\033[0m")
type_text("\033[32mGenerated 21 API specs\033[0m")
type_text("\033[32mGenerated 41 test cases\033[0m")
type_text("\033[32mGenerated 24 tasks\033[0m")
type_text("\033[32mGenerated 24 AI coding tasks\033[0m")
type_text("\033[1mAll artifacts written to outputs/\033[0m")
type_text("")
type_text("$ # Step 3: Review generated artifacts")
type_text("$ cat outputs/user_stories.md")
type_text("")
type_text("# User Stories")
type_text("")
type_text("## US-001: Upload attachments")
type_text("")
type_text("As a business user,")
type_text("I want to upload attachments to business documents,")
type_text("so that supporting materials can be stored and reviewed later.")
type_text("")
type_text("## US-002: Preview attachments")
type_text("")
type_text("As a user,")
type_text("I want to preview uploaded attachments,")
type_text("so that I can verify file content without downloading it.")
type_text("")
type_text("$ # Step 4: Generate test skeletons")
type_text("$ spec-harness generate-tests outputs/api_spec.yaml")
type_text("")
type_text("\033[32mGenerated pytest skeletons in outputs/tests/pytest/\033[0m")
type_text("\033[32mTest skeletons generated.\033[0m")
type_text("")
type_text("$ # Step 5: Validate traceability")
type_text("$ spec-harness validate outputs/")
type_text("")
type_text("\033[32mValidation passed: all required artifacts present.\033[0m")
type_text("")
type_text("$ # Step 6: Export AI coding tasks")
type_text("$ spec-harness export-agent-tasks outputs/task_breakdown.yaml")
type_text("")
type_text("\033[32mExported 6 agent tasks to outputs/agent_tasks/\033[0m")
type_text("")
type_text("$ # Ready to feed tasks to Claude Code / Codex!")
type_text("$ cat outputs/agent_tasks/TASK-001.md | head -20")
type_text("")
type_text("# TASK-001: Implement attachment domain model")
type_text("")
type_text("## Context")
type_text("This task is part of a feature implementation. Task type: backend.")
type_text("Related story: US-001. Focus on completing the specified scope.")
type_text("")
type_text("## Goal")
type_text("Complete implement attachment domain model and database schema")
type_text("")
type_text("$ # Full workflow from vague requirement to AI-ready tasks")
type_text("$ # in under 30 seconds. That's Spec-Driven Vibe Coding.")
type_text("")

sys.stdout.write("$ ")
sys.stdout.flush()

# Keep terminal open for viewing
import time
time.sleep(2)
